In [1]:
# install the library yfinance
# pip install yfinance

In [4]:
import pandas as pd
import sqlite3
import yfinance as yf

In [5]:
# create a sql connection and create the database stock
db_file = "data2.db"
conn = sqlite3.connect(db_file)

On cr√©e une table pour les prix

In [19]:
# create price table with the primary tuple keys ( date, ticker) and the columns, date, ticker, price
query1 = """CREATE TABLE IF NOT EXISTS price(
date DATE NOT NULL,
ticker TEXT NOT NULL,
price FLOAT,
PRIMARY KEY(date, ticker)
);"""
conn.execute(query1.replace('\n',' '))

In [20]:
# create volume table with the primary tuple keys ( date, ticker) and the columns, date, ticker, volume 
query2 = """CREATE TABLE IF NOT EXISTS volume (
Date TEXT NOT NULL,
ticker TEXT NOT NULL,
volume REAL,
PRIMARY KEY(Date, ticker)
)"""
conn.execute(query2.replace('\n', ' '))

In [21]:
# backtest inputs
bt_inputs = {'tickers': ['BA', 'UNH', 'MCD', 'HD'], #BA: Boeing, UNH: UnitedHealth, MCD: Mac Donalds, HD : HomeDepot
'start_date': '2019-01-01',
'end_date': '2021-06-01'}

In [22]:
def download(bt_inputs, proxy = None):
    data = yf.download(tickers= bt_inputs['tickers'],
                       start = bt_inputs['start_date'],   
                       end = bt_inputs['end_date'],
                       interval = '1d',
                       prepost = True,
                       threads = True,
                       proxy = proxy)
    return data

In [23]:
test = download(bt_inputs)

[*********************100%***********************]  4 of 4 completed

In [24]:
test

             Adj Close                                           Close  \
                    BA          HD         MCD         UNH          BA
Date
2019-01-02  314.645142  160.614792  163.065048  232.297791  323.809998
2019-01-03  302.100555  157.074738  161.990677  225.962967  310.899994
2019-01-04  317.822601  161.741989  165.121201  228.605652  327.079987
2019-01-07  318.823395  164.928024  166.917984  229.044525  328.109985
2019-01-08  330.891937  165.719864  167.269958  232.106964  340.529999
...                ...         ...         ...         ...         ...
2021-05-24  237.440002  310.329895  226.852051  406.691772  237.440002
2021-05-25  240.740005  312.212524  227.077042  408.769989  240.740005
2021-05-26  241.369995  312.784210  227.282471  408.928345  241.369995
2021-05-27  250.699997  314.203583  229.737717  408.423615  250.699997
2021-05-28  247.020004  314.341583  230.052460  407.651703  247.020004

                                                      High              ...  \
                    HD         MCD         UNH          BA          HD  ...
Date                                                                    ...
2019-01-02  172.410004  176.059998  243.490005  323.950012  173.179993  ...
2019-01-03  168.610001  174.899994  236.850006  319.739990  171.839996  ...
2019-01-04  173.619995  178.279999  239.619995  328.440002  174.740005  ...
2019-01-07  177.039993  180.220001  240.080002  330.690002  178.179993  ...
2019-01-08  177.889999  180.600006  243.289993  341.250000  179.589996  ...
...                ...         ...         ...         ...         ...  ...
2021-05-24  314.839996  231.910004  410.950012  238.500000  318.739990  ...
2021-05-25  316.750000  232.139999  413.049988  243.779999  317.100006  ...
2021-05-26  317.329987  232.350006  413.209991  242.490005  321.380005  ...
2021-05-27  318.769989  234.860001  412.700012  252.600006  320.410004  ...
2021-05-28  318.910004  233.889999  411.920013  248.979996  321.510010  ...

                   Low                    Open                          \
                   MCD         UNH          BA          HD         MCD
Date
2019-01-02  174.169998  241.470001  316.190002  169.710007  175.410004
2019-01-03  174.410004  236.130005  319.489990  171.839996  175.449997
2019-01-04  175.690002  238.800003  316.690002  170.179993  176.029999
2019-01-07  178.139999  238.229996  330.519989  173.830002  178.139999
2019-01-08  179.910004  239.710007  334.109985  178.570007  181.960007
...                ...         ...         ...         ...         ...
2021-05-24  231.020004  409.920013  235.139999  316.839996  231.520004
2021-05-25  230.710007  408.890015  240.000000  315.529999  232.169998
2021-05-26  232.160004  411.010010  241.699997  317.809998  233.789993
2021-05-27  232.399994  410.380005  248.110001  317.299988  233.009995
2021-05-28  232.449997  410.019989  247.479996  320.369995  234.130005

                          Volume
                   UNH        BA       HD      MCD      UNH
Date
2019-01-02  245.000000   3292200  4242900  2571500  4063600
2019-01-03  243.479996   5705600  4810500  3728200  4623200
2019-01-04  239.800003   4448800  4762600  3194300  5367600
2019-01-07  240.399994   4030300  4928800  3283000  4133000
2019-01-08  242.330002   4736500  4722400  2941400  3618600
...                ...       ...      ...      ...      ...
2021-05-24  412.369995  10106000  2930600  1823300  1883600
2021-05-25  411.850006  12908000  3523300  2681900  2285600
2021-05-26  412.100006   7240200  2881600  1564200  1903900
2021-05-27  414.920013  18404400  3734800  5242900  2041800
2021-05-28  412.700012  11197400  3194000  2853600  2367900

[607 rows x 24 columns]

In [25]:
test['Adj Close']

                    BA          HD         MCD         UNH
Date
2019-01-02  314.645142  160.614792  163.065048  232.297791
2019-01-03  302.100555  157.074738  161.990677  225.962967
2019-01-04  317.822601  161.741989  165.121201  228.605652
2019-01-07  318.823395  164.928024  166.917984  229.044525
2019-01-08  330.891937  165.719864  167.269958  232.106964
...                ...         ...         ...         ...
2021-05-24  237.440002  310.329895  226.852051  406.691772
2021-05-25  240.740005  312.212524  227.077042  408.769989
2021-05-26  241.369995  312.784210  227.282471  408.928345
2021-05-27  250.699997  314.203583  229.737717  408.423615
2021-05-28  247.020004  314.341583  230.052460  407.651703

[607 rows x 4 columns]

In [26]:
test['Volume']

                  BA       HD      MCD      UNH
Date
2019-01-02   3292200  4242900  2571500  4063600
2019-01-03   5705600  4810500  3728200  4623200
2019-01-04   4448800  4762600  3194300  5367600
2019-01-07   4030300  4928800  3283000  4133000
2019-01-08   4736500  4722400  2941400  3618600
...              ...      ...      ...      ...
2021-05-24  10106000  2930600  1823300  1883600
2021-05-25  12908000  3523300  2681900  2285600
2021-05-26   7240200  2881600  1564200  1903900
2021-05-27  18404400  3734800  5242900  2041800
2021-05-28  11197400  3194000  2853600  2367900

[607 rows x 4 columns]

In [27]:
adj_close = test['Adj Close']
volume = test['Volume']

In [28]:
adj_close.head()

                    BA          HD         MCD         UNH
Date
2019-01-02  314.645142  160.614792  163.065048  232.297791
2019-01-03  302.100555  157.074738  161.990677  225.962967
2019-01-04  317.822601  161.741989  165.121201  228.605652
2019-01-07  318.823395  164.928024  166.917984  229.044525
2019-01-08  330.891937  165.719864  167.269958  232.106964

In [29]:
# convert wide to long
adj_close_long = pd.melt(adj_close.reset_index(), id_vars='Date', value_vars=bt_inputs['tickers'], 
                         var_name ="ticker", value_name="price")
adj_close_long

           Date ticker       price
0    2019-01-02     BA  314.645142
1    2019-01-03     BA  302.100555
2    2019-01-04     BA  317.822601
3    2019-01-07     BA  318.823395
4    2019-01-08     BA  330.891937
...         ...    ...         ...
2423 2021-05-24     HD  310.329895
2424 2021-05-25     HD  312.212524
2425 2021-05-26     HD  312.784210
2426 2021-05-27     HD  314.203583
2427 2021-05-28     HD  314.341583

[2428 rows x 3 columns]

In [30]:
adj_close_long[0:607]

          Date ticker       price
0   2019-01-02     BA  314.645142
1   2019-01-03     BA  302.100555
2   2019-01-04     BA  317.822601
3   2019-01-07     BA  318.823395
4   2019-01-08     BA  330.891937
..         ...    ...         ...
602 2021-05-24     BA  237.440002
603 2021-05-25     BA  240.740005
604 2021-05-26     BA  241.369995
605 2021-05-27     BA  250.699997
606 2021-05-28     BA  247.020004

[607 rows x 3 columns]

In [31]:
adj_close_long[607:1215]

           Date ticker       price
607  2019-01-02    UNH  232.297791
608  2019-01-03    UNH  225.962967
609  2019-01-04    UNH  228.605652
610  2019-01-07    UNH  229.044525
611  2019-01-08    UNH  232.106964
...         ...    ...         ...
1210 2021-05-25    UNH  408.769989
1211 2021-05-26    UNH  408.928345
1212 2021-05-27    UNH  408.423615
1213 2021-05-28    UNH  407.651703
1214 2019-01-02    MCD  163.065048

[608 rows x 3 columns]

In [32]:
adj_close_long['ticker'].value_counts()

BA     607
UNH    607
MCD    607
HD     607
Name: ticker, dtype: int64

In [33]:
volume

                  BA       HD      MCD      UNH
Date
2019-01-02   3292200  4242900  2571500  4063600
2019-01-03   5705600  4810500  3728200  4623200
2019-01-04   4448800  4762600  3194300  5367600
2019-01-07   4030300  4928800  3283000  4133000
2019-01-08   4736500  4722400  2941400  3618600
...              ...      ...      ...      ...
2021-05-24  10106000  2930600  1823300  1883600
2021-05-25  12908000  3523300  2681900  2285600
2021-05-26   7240200  2881600  1564200  1903900
2021-05-27  18404400  3734800  5242900  2041800
2021-05-28  11197400  3194000  2853600  2367900

[607 rows x 4 columns]

In [34]:
#convert wide to long
volume_long = pd.melt(volume.reset_index(), id_vars='Date', value_vars=bt_inputs['tickers'], 
                      var_name = "ticker", value_name = "volume")
volume_long.head()

        Date ticker   volume
0 2019-01-02     BA  3292200
1 2019-01-03     BA  5705600
2 2019-01-04     BA  4448800
3 2019-01-07     BA  4030300
4 2019-01-08     BA  4736500

In [35]:
# insert a in sql table prices and volume
#YOUR CODE
volume_long.to_sql("volume", conn, if_exists="replace", index=False)
adj_close_long.to_sql("price", conn, if_exists="replace", index=False)

2428

In [36]:
select_tickers = bt_inputs['tickers']
select_tickers

['BA', 'UNH', 'MCD', 'HD']

In [37]:
start_date = bt_inputs['start_date']
start_date

'2019-01-01'

In [44]:
# inputs
select_tickers = bt_inputs['tickers']
start_date = bt_inputs['start_date']
end_date = bt_inputs['end_date']
# construct query: select the prices withe tickers in select_tickers 
#between start_date and end_date
query = """ SELECT * 
FROM price
WHERE ticker in ('"""+ "','".join(select_tickers) + """') AND Date >= '"""+ start_date + """' and Date < '""" + end_date + "'" 
conn.execute(query.replace('\n',' '))

In [51]:
#display the request
#YOUR CODE
liste=[]
cur = conn.cursor()
for row in cur.execute(query.replace('\n',' ')):
    print(row)

('2019-01-02 00:00:00', 'BA', 314.6451416015625)
('2019-01-03 00:00:00', 'BA', 302.1005554199219)
('2019-01-04 00:00:00', 'BA', 317.8226013183594)
('2019-01-07 00:00:00', 'BA', 318.8233947753906)
('2019-01-08 00:00:00', 'BA', 330.8919372558594)
('2019-01-09 00:00:00', 'BA', 334.0984802246094)
('2019-01-10 00:00:00', 'BA', 342.6300048828125)
('2019-01-11 00:00:00', 'BA', 342.9118347167969)
('2019-01-14 00:00:00', 'BA', 340.4436950683594)
('2019-01-15 00:00:00', 'BA', 342.2705078125)
('2019-01-16 00:00:00', 'BA', 342.0955505371094)
('2019-01-17 00:00:00', 'BA', 348.9266357421875)
('2019-01-18 00:00:00', 'BA', 354.4070129394531)
('2019-01-22 00:00:00', 'BA', 347.77032470703125)
('2019-01-23 00:00:00', 'BA', 348.460205078125)
('2019-01-24 00:00:00', 'BA', 348.12982177734375)
('2019-01-25 00:00:00', 'BA', 353.8919677734375)
('2019-01-28 00:00:00', 'BA', 352.69677734375)
('2019-01-29 00:00:00', 'BA', 354.5819091796875)
('2019-01-30 00:00:00', 'BA', 376.74627685546875)
('2019-01-31 00:00:00', 'BA', 374.7056884765625)
('2019-02-01 00:00:00', 'BA', 376.4645080566406)
('2019-02-04 00:00:00', 'BA', 385.7636413574219)
('2019-02-05 00:00:00', 'BA', 398.570556640625)
('2019-02-06 00:00:00', 'BA', 399.4742431640625)
('2019-02-07 00:00:00', 'BA', 395.6802673339844)
('2019-02-08 00:00:00', 'BA', 395.4263610839844)
('2019-02-11 00:00:00', 'BA', 394.4888610839844)
('2019-02-12 00:00:00', 'BA', 401.1003112792969)
('2019-02-13 00:00:00', 'BA', 400.9635925292969)
('2019-02-14 00:00:00', 'BA', 400.2213439941406)
('2019-02-15 00:00:00', 'BA', 408.1805114746094)
('2019-02-19 00:00:00', 'BA', 406.5105285644531)
('2019-02-20 00:00:00', 'BA', 411.6766357421875)
('2019-02-21 00:00:00', 'BA', 407.79962158203125)
('2019-02-22 00:00:00', 'BA', 414.1180725097656)
('2019-02-25 00:00:00', 'BA', 416.8720397949219)
('2019-02-26 00:00:00', 'BA', 416.77435302734375)
('2019-02-27 00:00:00', 'BA', 425.2413024902344)
('2019-02-28 00:00:00', 'BA', 429.6554260253906)
('2019-03-01 00:00:00', 'BA', 430.29998779296875)
('2019-03-04 00:00:00', 'BA', 422.55572509765625)
('2019-03-05 00:00:00', 'BA', 420.0458984375)
('2019-03-06 00:00:00', 'BA', 414.5184631347656)
('2019-03-07 00:00:00', 'BA', 412.6629638671875)
('2019-03-08 00:00:00', 'BA', 412.6434631347656)
('2019-03-11 00:00:00', 'BA', 390.6411437988281)
('2019-03-12 00:00:00', 'BA', 366.6173095703125)
('2019-03-13 00:00:00', 'BA', 368.30682373046875)
('2019-03-14 00:00:00', 'BA', 364.55670166015625)
('2019-03-15 00:00:00', 'BA', 370.1134338378906)
('2019-03-18 00:00:00', 'BA', 363.5606384277344)
('2019-03-19 00:00:00', 'BA', 364.6836853027344)
('2019-03-20 00:00:00', 'BA', 367.3497619628906)
('2019-03-21 00:00:00', 'BA', 363.9707946777344)
('2019-03-22 00:00:00', 'BA', 353.68743896484375)
('2019-03-25 00:00:00', 'BA', 361.783203125)
('2019-03-26 00:00:00', 'BA', 361.7051086425781)
('2019-03-27 00:00:00', 'BA', 365.4454040527344)
('2019-03-28 00:00:00', 'BA', 365.6700439453125)
('2019-03-29 00:00:00', 'BA', 372.486572265625)
('2019-04-01 00:00:00', 'BA', 382.3695373535156)
('2019-04-02 00:00:00', 'BA', 381.5979919433594)
('2019-04-03 00:00:00', 'BA', 375.728759765625)
('2019-04-04 00:00:00', 'BA', 386.5883483886719)
('2019-04-05 00:00:00', 'BA', 382.7503356933594)
('2019-04-08 00:00:00', 'BA', 365.7481689453125)
('2019-04-09 00:00:00', 'BA', 360.3965148925781)
('2019-04-10 00:00:00', 'BA', 356.39251708984375)
('2019-04-11 00:00:00', 'BA', 361.49029541015625)
('2019-04-12 00:00:00', 'BA', 370.74822998046875)
('2019-04-15 00:00:00', 'BA', 366.6661071777344)
('2019-04-16 00:00:00', 'BA', 372.7795104980469)
('2019-04-17 00:00:00', 'BA', 368.6778869628906)
('2019-04-18 00:00:00', 'BA', 371.1681823730469)
('2019-04-22 00:00:00', 'BA', 366.3829650878906)
('2019-04-23 00:00:00', 'BA', 365.25982666015625)
('2019-04-24 00:00:00', 'BA', 366.6661071777344)
('2019-04-25 00:00:00', 'BA', 373.834228515625)
('2019-04-26 00:00:00', 'BA', 371.87127685546875)
('2019-04-29 00:00:00', 'BA', 370.17205810546875)
('2019-04-30 00:00:00', 'BA', 368.8439025878906)
('2019-05-01 00:00:00', 'BA', 367.9747619628906)
('2019-05-02 00:00:00', 'BA', 366.9981689453125)
('2019-05-03 00:00:00', 'BA', 367.6427001953125)
('2019-05-06 00:00:00', 'BA', 362.89654541015625)
('2019-05-07 00:00:00', 'BA', 348.86309814453125)
('2019-05-08 00:00:00', 'BA', 351.3240661621094)
('2019-05-09 00:00:00', 'BA', 347.82257080078125)
('2019-05-10 00:00:00', 'BA', 348.35296630859375)
('2019-05-13 00:00:00', 'BA', 331.361083984375)
('2019-05-14 00:00:00', 'BA', 336.93011474609375)
('2019-05-15 00:00:00', 'BA', 339.48382568359375)
('2019-05-16 00:00:00', 'BA', 347.5082702636719)
('2019-05-17 00:00:00', 'BA', 348.69671630859375)
('2019-05-20 00:00:00', 'BA', 346.5064697265625)
('2019-05-21 00:00:00', 'BA', 352.36029052734375)
('2019-05-22 00:00:00', 'BA', 346.4966125488281)
('2019-05-23 00:00:00', 'BA', 344.30633544921875)
('2019-05-24 00:00:00', 'BA', 348.578857421875)
('2019-05-28 00:00:00', 'BA', 348.5592346191406)
('2019-05-29 00:00:00', 'BA', 342.5874938964844)
('2019-05-30 00:00:00', 'BA', 343.638427734375)
('2019-05-31 00:00:00', 'BA', 335.52557373046875)
('2019-06-03 00:00:00', 'BA', 332.8540344238281)
('2019-06-04 00:00:00', 'BA', 338.4819641113281)
('2019-06-05 00:00:00', 'BA', 342.53839111328125)
('2019-06-06 00:00:00', 'BA', 344.394775390625)
('2019-06-07 00:00:00', 'BA', 347.4002685546875)
('2019-06-10 00:00:00', 'BA', 347.4984436035156)
('2019-06-11 00:00:00', 'BA', 343.1080627441406)
('2019-06-12 00:00:00', 'BA', 340.8490295410156)
('2019-06-13 00:00:00', 'BA', 342.64642333984375)
('2019-06-14 00:00:00', 'BA', 340.9767150878906)
('2019-06-17 00:00:00', 'BA', 348.578857421875)
('2019-06-18 00:00:00', 'BA', 367.29937744140625)
('2019-06-19 00:00:00', 'BA', 361.9955749511719)
('2019-06-20 00:00:00', 'BA', 368.2030029296875)
('2019-06-21 00:00:00', 'BA', 365.2171325683594)
('2019-06-24 00:00:00', 'BA', 367.3288269042969)
('2019-06-25 00:00:00', 'BA', 362.74200439453125)
('2019-06-26 00:00:00', 'BA', 368.26190185546875)
('2019-06-27 00:00:00', 'BA', 357.5364074707031)
('2019-06-28 00:00:00', 'BA', 357.5265808105469)
('2019-07-01 00:00:00', 'BA', 350.111083984375)
('2019-07-02 00:00:00', 'BA', 347.85205078125)
('2019-07-03 00:00:00', 'BA', 348.156494140625)
('2019-07-05 00:00:00', 'BA', 349.521728515625)
('2019-07-08 00:00:00', 'BA', 344.8661804199219)
('2019-07-09 00:00:00', 'BA', 346.8011169433594)
('2019-07-10 00:00:00', 'BA', 346.025146484375)
('2019-07-11 00:00:00', 'BA', 352.6058349609375)
('2019-07-12 00:00:00', 'BA', 358.8230895996094)
('2019-07-15 00:00:00', 'BA', 355.1693420410156)
('2019-07-16 00:00:00', 'BA', 356.2890319824219)
('2019-07-17 00:00:00', 'BA', 362.9384765625)
('2019-07-18 00:00:00', 'BA', 354.67822265625)
('2019-07-19 00:00:00', 'BA', 370.6387939453125)
('2019-07-22 00:00:00', 'BA', 366.76904296875)
('2019-07-23 00:00:00', 'BA', 366.4252624511719)
('2019-07-24 00:00:00', 'BA', 354.9925537109375)
('2019-07-25 00:00:00', 'BA', 341.8901672363281)
('2019-07-26 00:00:00', 'BA', 338.8551940917969)
('2019-07-29 00:00:00', 'BA', 334.1504821777344)
('2019-07-30 00:00:00', 'BA', 341.2713623046875)
('2019-07-31 00:00:00', 'BA', 335.10321044921875)
('2019-08-01 00:00:00', 'BA', 328.3359375)
('2019-08-02 00:00:00', 'BA', 333.5120849609375)
('2019-08-05 00:00:00', 'BA', 325.1634521484375)
('2019-08-06 00:00:00', 'BA', 326.52874755859375)
('2019-08-07 00:00:00', 'BA', 325.477783203125)
('2019-08-08 00:00:00', 'BA', 332.42071533203125)
('2019-08-09 00:00:00', 'BA', 333.606689453125)
('2019-08-12 00:00:00', 'BA', 329.050537109375)
('2019-08-13 00:00:00', 'BA', 328.9714660644531)
('2019-08-14 00:00:00', 'BA', 316.6767883300781)
('2019-08-15 00:00:00', 'BA', 324.1682434082031)
('2019-08-16 00:00:00', 'BA', 326.58966064453125)
('2019-08-19 00:00:00', 'BA', 329.8807067871094)
('2019-08-20 00:00:00', 'BA', 327.87445068359375)
('2019-08-21 00:00:00', 'BA', 336.0181884765625)
('2019-08-22 00:00:00', 'BA', 350.26971435546875)
('2019-08-23 00:00:00', 'BA', 351.8510437011719)
('2019-08-26 00:00:00', 'BA', 354.84564208984375)
('2019-08-27 00:00:00', 'BA', 350.58599853515625)
('2019-08-28 00:00:00', 'BA', 355.7647705078125)
('2019-08-29 00:00:00', 'BA', 358.5024108886719)
('2019-08-30 00:00:00', 'BA', 359.8366394042969)
('2019-09-03 00:00:00', 'BA', 350.2796325683594)
('2019-09-04 00:00:00', 'BA', 352.3649597167969)
('2019-09-05 00:00:00', 'BA', 356.09088134765625)
('2019-09-06 00:00:00', 'BA', 358.7593688964844)
('2019-09-09 00:00:00', 'BA', 354.5886535644531)
('2019-09-10 00:00:00', 'BA', 365.17352294921875)
('2019-09-11 00:00:00', 'BA', 378.4664306640625)
('2019-09-12 00:00:00', 'BA', 371.2418212890625)
('2019-09-13 00:00:00', 'BA', 375.3235778808594)
('2019-09-16 00:00:00', 'BA', 374.4241943359375)
('2019-09-17 00:00:00', 'BA', 379.7117004394531)
('2019-09-18 00:00:00', 'BA', 381.8959045410156)
('2019-09-19 00:00:00', 'BA', 379.94891357421875)
('2019-09-20 00:00:00', 'BA', 374.9579162597656)
('2019-09-23 00:00:00', 'BA', 372.6254577636719)
('2019-09-24 00:00:00', 'BA', 377.1914978027344)
('2019-09-25 00:00:00', 'BA', 381.6883544921875)
('2019-09-26 00:00:00', 'BA', 382.37030029296875)
('2019-09-27 00:00:00', 'BA', 378.3873596191406)
('2019-09-30 00:00:00', 'BA', 376.0252685546875)
('2019-10-01 00:00:00', 'BA', 370.55987548828125)
('2019-10-02 00:00:00', 'BA', 363.06842041015625)
('2019-10-03 00:00:00', 'BA', 367.7234191894531)
('2019-10-04 00:00:00', 'BA', 371.31103515625)
('2019-10-07 00:00:00', 'BA', 372.1412048339844)
('2019-10-08 00:00:00', 'BA', 369.7297058105469)
('2019-10-09 00:00:00', 'BA', 370.57965087890625)
('2019-10-10 00:00:00', 'BA', 366.6659240722656)
('2019-10-11 00:00:00', 'BA', 370.5401306152344)
('2019-10-14 00:00:00', 'BA', 368.8204345703125)
('2019-10-15 00:00:00', 'BA', 366.6263732910156)
('2019-10-16 00:00:00', 'BA', 368.0792236328125)
('2019-10-17 00:00:00', 'BA', 364.74859619140625)
('2019-10-18 00:00:00', 'BA', 339.9813537597656)
('2019-10-21 00:00:00', 'BA', 327.1924743652344)
('2019-10-22 00:00:00', 'BA', 333.0631103515625)
('2019-10-23 00:00:00', 'BA', 336.522216796875)
('2019-10-24 00:00:00', 'BA', 340.52490234375)
('2019-10-25 00:00:00', 'BA', 335.86004638671875)
('2019-10-28 00:00:00', 'BA', 336.89776611328125)
('2019-10-29 00:00:00', 'BA', 344.8537292480469)
('2019-10-30 00:00:00', 'BA', 342.01727294921875)
('2019-10-31 00:00:00', 'BA', 335.9391174316406)
('2019-11-01 00:00:00', 'BA', 341.1574401855469)
('2019-11-04 00:00:00', 'BA', 346.9884948730469)
('2019-11-05 00:00:00', 'BA', 354.1044006347656)
('2019-11-06 00:00:00', 'BA', 350.05230712890625)
('2019-11-07 00:00:00', 'BA', 355.1966857910156)
('2019-11-08 00:00:00', 'BA', 348.92401123046875)
('2019-11-11 00:00:00', 'BA', 364.78961181640625)
('2019-11-12 00:00:00', 'BA', 360.7337341308594)
('2019-11-13 00:00:00', 'BA', 360.3559875488281)
('2019-11-14 00:00:00', 'BA', 365.26678466796875)
('2019-11-15 00:00:00', 'BA', 369.481689453125)
('2019-11-18 00:00:00', 'BA', 367.2748107910156)
('2019-11-19 00:00:00', 'BA', 364.8293762207031)
('2019-11-20 00:00:00', 'BA', 368.71624755859375)
('2019-11-21 00:00:00', 'BA', 364.2726745605469)
('2019-11-22 00:00:00', 'BA', 369.1437072753906)
('2019-11-25 00:00:00', 'BA', 370.9231262207031)
('2019-11-26 00:00:00', 'BA', 371.3008728027344)
('2019-11-27 00:00:00', 'BA', 365.8234558105469)
('2019-11-29 00:00:00', 'BA', 364.01422119140625)
('2019-12-02 00:00:00', 'BA', 353.07928466796875)
('2019-12-03 00:00:00', 'BA', 349.99761962890625)
('2019-12-04 00:00:00', 'BA', 346.7767639160156)
('2019-12-05 00:00:00', 'BA', 343.6354675292969)
('2019-12-06 00:00:00', 'BA', 351.9957275390625)
('2019-12-09 00:00:00', 'BA', 349.13275146484375)
('2019-12-10 00:00:00', 'BA', 345.84234619140625)
('2019-12-11 00:00:00', 'BA', 347.929931640625)
('2019-12-12 00:00:00', 'BA', 344.24188232421875)
('2019-12-13 00:00:00', 'BA', 339.6492004394531)
('2019-12-16 00:00:00', 'BA', 325.0659484863281)
('2019-12-17 00:00:00', 'BA', 325.0659484863281)
('2019-12-18 00:00:00', 'BA', 328.72418212890625)
('2019-12-19 00:00:00', 'BA', 331.5274963378906)
('2019-12-20 00:00:00', 'BA', 326.0600280761719)
('2019-12-23 00:00:00', 'BA', 335.5535583496094)
('2019-12-24 00:00:00', 'BA', 331.03045654296875)
('2019-12-26 00:00:00', 'BA', 327.96868896484375)
('2019-12-27 00:00:00', 'BA', 328.1874084472656)
('2019-12-30 00:00:00', 'BA', 324.4695129394531)
('2019-12-31 00:00:00', 'BA', 323.83331298828125)
('2020-01-02 00:00:00', 'BA', 331.34857177734375)
('2020-01-03 00:00:00', 'BA', 330.7919006347656)
('2020-01-06 00:00:00', 'BA', 331.7660827636719)
('2020-01-07 00:00:00', 'BA', 335.28515625)
('2020-01-08 00:00:00', 'BA', 329.41009521484375)
('2020-01-09 00:00:00', 'BA', 334.3507080078125)
('2020-01-10 00:00:00', 'BA', 327.96868896484375)
('2020-01-13 00:00:00', 'BA', 328.26690673828125)
('2020-01-14 00:00:00', 'BA', 330.3843078613281)
('2020-01-15 00:00:00', 'BA', 327.8493957519531)
('2020-01-16 00:00:00', 'BA', 330.036376953125)
('2020-01-17 00:00:00', 'BA', 322.2328186035156)
('2020-01-21 00:00:00', 'BA', 311.5165710449219)
('2020-01-22 00:00:00', 'BA', 307.17242431640625)
('2020-01-23 00:00:00', 'BA', 315.9104309082031)
('2020-01-24 00:00:00', 'BA', 321.1393127441406)
('2020-01-27 00:00:00', 'BA', 314.72747802734375)
('2020-01-28 00:00:00', 'BA', 314.6877136230469)
('2020-01-29 00:00:00', 'BA', 320.1153869628906)
('2020-01-30 00:00:00', 'BA', 321.3878173828125)
('2020-01-31 00:00:00', 'BA', 316.3875732421875)
('2020-02-03 00:00:00', 'BA', 314.1310119628906)
('2020-02-04 00:00:00', 'BA', 316.0595397949219)
('2020-02-05 00:00:00', 'BA', 327.6008605957031)
('2020-02-06 00:00:00', 'BA', 339.4106140136719)
('2020-02-07 00:00:00', 'BA', 334.75830078125)
('2020-02-10 00:00:00', 'BA', 342.6314697265625)
('2020-02-11 00:00:00', 'BA', 342.3829345703125)
('2020-02-12 00:00:00', 'BA', 345.39501953125)
('2020-02-13 00:00:00', 'BA', 342.82000732421875)
('2020-02-14 00:00:00', 'BA', 340.489990234375)
('2020-02-18 00:00:00', 'BA', 338.8800048828125)
('2020-02-19 00:00:00', 'BA', 338.29998779296875)
('2020-02-20 00:00:00', 'BA', 336.2799987792969)
('2020-02-21 00:00:00', 'BA', 330.3800048828125)
('2020-02-24 00:00:00', 'BA', 317.8999938964844)
('2020-02-25 00:00:00', 'BA', 304.1400146484375)
('2020-02-26 00:00:00', 'BA', 305.5899963378906)
('2020-02-27 00:00:00', 'BA', 287.760009765625)
('2020-02-28 00:00:00', 'BA', 275.1099853515625)
('2020-03-02 00:00:00', 'BA', 289.2699890136719)
('2020-03-03 00:00:00', 'BA', 280.6199951171875)
('2020-03-04 00:00:00', 'BA', 283.1199951171875)
('2020-03-05 00:00:00', 'BA', 260.3699951171875)
('2020-03-06 00:00:00', 'BA', 262.3299865722656)
('2020-03-09 00:00:00', 'BA', 227.1699981689453)
('2020-03-10 00:00:00', 'BA', 231.00999450683594)
('2020-03-11 00:00:00', 'BA', 189.0800018310547)
('2020-03-12 00:00:00', 'BA', 154.83999633789062)
('2020-03-13 00:00:00', 'BA', 170.1999969482422)
('2020-03-16 00:00:00', 'BA', 129.61000061035156)
('2020-03-17 00:00:00', 'BA', 124.13999938964844)
('2020-03-18 00:00:00', 'BA', 101.88999938964844)
('2020-03-19 00:00:00', 'BA', 97.70999908447266)
('2020-03-20 00:00:00', 'BA', 95.01000213623047)
('2020-03-23 00:00:00', 'BA', 105.62000274658203)
('2020-03-24 00:00:00', 'BA', 127.68000030517578)
('2020-03-25 00:00:00', 'BA', 158.72999572753906)
('2020-03-26 00:00:00', 'BA', 180.5500030517578)
('2020-03-27 00:00:00', 'BA', 162.0)
('2020-03-30 00:00:00', 'BA', 152.27999877929688)
('2020-03-31 00:00:00', 'BA', 149.13999938964844)
('2020-04-01 00:00:00', 'BA', 130.6999969482422)
('2020-04-02 00:00:00', 'BA', 123.2699966430664)
('2020-04-03 00:00:00', 'BA', 124.5199966430664)
('2020-04-06 00:00:00', 'BA', 148.77000427246094)
('2020-04-07 00:00:00', 'BA', 141.5800018310547)
('2020-04-08 00:00:00', 'BA', 146.8699951171875)
('2020-04-09 00:00:00', 'BA', 151.83999633789062)
('2020-04-13 00:00:00', 'BA', 147.3300018310547)
('2020-04-14 00:00:00', 'BA', 141.0)
('2020-04-15 00:00:00', 'BA', 145.97999572753906)
('2020-04-16 00:00:00', 'BA', 134.24000549316406)
('2020-04-17 00:00:00', 'BA', 154.0)
('2020-04-20 00:00:00', 'BA', 143.61000061035156)
('2020-04-21 00:00:00', 'BA', 136.3300018310547)
('2020-04-22 00:00:00', 'BA', 134.97000122070312)
('2020-04-23 00:00:00', 'BA', 137.74000549316406)
('2020-04-24 00:00:00', 'BA', 128.97999572753906)
('2020-04-27 00:00:00', 'BA', 128.67999267578125)
('2020-04-28 00:00:00', 'BA', 131.3000030517578)
('2020-04-29 00:00:00', 'BA', 139.0)
('2020-04-30 00:00:00', 'BA', 141.02000427246094)
('2020-05-01 00:00:00', 'BA', 133.3699951171875)
('2020-05-04 00:00:00', 'BA', 131.4600067138672)
('2020-05-05 00:00:00', 'BA', 125.4000015258789)
('2020-05-06 00:00:00', 'BA', 121.86000061035156)
('2020-05-07 00:00:00', 'BA', 128.64999389648438)
('2020-05-08 00:00:00', 'BA', 133.44000244140625)
('2020-05-11 00:00:00', 'BA', 128.91000366210938)
('2020-05-12 00:00:00', 'BA', 125.22000122070312)
('2020-05-13 00:00:00', 'BA', 121.5)
('2020-05-14 00:00:00', 'BA', 122.5199966430664)
('2020-05-15 00:00:00', 'BA', 120.0)
('2020-05-18 00:00:00', 'BA', 135.44000244140625)
('2020-05-19 00:00:00', 'BA', 130.44000244140625)
('2020-05-20 00:00:00', 'BA', 133.32000732421875)
('2020-05-21 00:00:00', 'BA', 139.0)
('2020-05-22 00:00:00', 'BA', 137.52999877929688)
('2020-05-26 00:00:00', 'BA', 144.72999572753906)
('2020-05-27 00:00:00', 'BA', 149.52000427246094)
('2020-05-28 00:00:00', 'BA', 149.82000732421875)
('2020-05-29 00:00:00', 'BA', 145.85000610351562)
('2020-06-01 00:00:00', 'BA', 151.38999938964844)
('2020-06-02 00:00:00', 'BA', 153.30999755859375)
('2020-06-03 00:00:00', 'BA', 173.16000366210938)
('2020-06-04 00:00:00', 'BA', 184.3000030517578)
('2020-06-05 00:00:00', 'BA', 205.42999267578125)
('2020-06-08 00:00:00', 'BA', 230.5)
('2020-06-09 00:00:00', 'BA', 216.74000549316406)
('2020-06-10 00:00:00', 'BA', 203.41000366210938)
('2020-06-11 00:00:00', 'BA', 170.0)
('2020-06-12 00:00:00', 'BA', 189.50999450683594)
('2020-06-15 00:00:00', 'BA', 190.94000244140625)
('2020-06-16 00:00:00', 'BA', 197.77000427246094)
('2020-06-17 00:00:00', 'BA', 192.5399932861328)
('2020-06-18 00:00:00', 'BA', 192.2899932861328)
('2020-06-19 00:00:00', 'BA', 187.02000427246094)
('2020-06-22 00:00:00', 'BA', 188.52000427246094)
('2020-06-23 00:00:00', 'BA', 187.8800048828125)
('2020-06-24 00:00:00', 'BA', 176.69000244140625)
('2020-06-25 00:00:00', 'BA', 174.8800048828125)
('2020-06-26 00:00:00', 'BA', 170.00999450683594)
('2020-06-29 00:00:00', 'BA', 194.49000549316406)
('2020-06-30 00:00:00', 'BA', 183.3000030517578)
('2020-07-01 00:00:00', 'BA', 180.32000732421875)
('2020-07-02 00:00:00', 'BA', 180.80999755859375)
('2020-07-06 00:00:00', 'BA', 187.91000366210938)
('2020-07-07 00:00:00', 'BA', 178.8800048828125)
('2020-07-08 00:00:00', 'BA', 180.0800018310547)
('2020-07-09 00:00:00', 'BA', 173.27999877929688)
('2020-07-10 00:00:00', 'BA', 178.44000244140625)
('2020-07-13 00:00:00', 'BA', 175.64999389648438)
('2020-07-14 00:00:00', 'BA', 179.9600067138672)
('2020-07-15 00:00:00', 'BA', 187.94000244140625)
('2020-07-16 00:00:00', 'BA', 178.6999969482422)
('2020-07-17 00:00:00', 'BA', 175.66000366210938)
('2020-07-20 00:00:00', 'BA', 174.4199981689453)
('2020-07-21 00:00:00', 'BA', 178.6300048828125)
('2020-07-22 00:00:00', 'BA', 179.7899932861328)
('2020-07-23 00:00:00', 'BA', 176.4499969482422)
('2020-07-24 00:00:00', 'BA', 173.75999450683594)
('2020-07-27 00:00:00', 'BA', 170.2100067138672)
('2020-07-28 00:00:00', 'BA', 170.83999633789062)
('2020-07-29 00:00:00', 'BA', 166.00999450683594)
('2020-07-30 00:00:00', 'BA', 161.9499969482422)
('2020-07-31 00:00:00', 'BA', 158.0)
('2020-08-03 00:00:00', 'BA', 162.27000427246094)
('2020-08-04 00:00:00', 'BA', 165.07000732421875)
('2020-08-05 00:00:00', 'BA', 174.27999877929688)
('2020-08-06 00:00:00', 'BA', 172.1999969482422)
('2020-08-07 00:00:00', 'BA', 170.02000427246094)
('2020-08-10 00:00:00', 'BA', 179.41000366210938)
('2020-08-11 00:00:00', 'BA', 180.1300048828125)
('2020-08-12 00:00:00', 'BA', 175.44000244140625)
('2020-08-13 00:00:00', 'BA', 174.72999572753906)
('2020-08-14 00:00:00', 'BA', 178.0800018310547)

('2019-01-04 00:00:00', 'MCD', 165.12120056152344)
('2019-01-07 00:00:00', 'MCD', 166.91798400878906)
('2019-01-08 00:00:00', 'MCD', 167.26995849609375)
('2019-01-09 00:00:00', 'MCD', 166.9828338623047)
('2019-01-10 00:00:00', 'MCD', 168.1498260498047)
('2019-01-11 00:00:00', 'MCD', 168.90928649902344)
('2019-01-14 00:00:00', 'MCD', 167.8441925048828)
('2019-01-15 00:00:00', 'MCD', 167.65895080566406)
('2019-01-16 00:00:00', 'MCD', 166.1122283935547)
('2019-01-17 00:00:00', 'MCD', 167.7423095703125)
('2019-01-18 00:00:00', 'MCD', 169.0945587158203)
('2019-01-22 00:00:00', 'MCD', 170.94691467285156)
('2019-01-23 00:00:00', 'MCD', 172.3546905517578)
('2019-01-24 00:00:00', 'MCD', 173.5402374267578)
('2019-01-25 00:00:00', 'MCD', 170.4189910888672)
('2019-01-28 00:00:00', 'MCD', 170.04852294921875)
('2019-01-29 00:00:00', 'MCD', 168.72406005859375)
('2019-01-30 00:00:00', 'MCD', 168.35362243652344)
('2019-01-31 00:00:00', 'MCD', 165.5842742919922)
('2019-02-01 00:00:00', 'MCD', 163.6763153076172)
('2019-02-04 00:00:00', 'MCD', 164.44509887695312)
('2019-02-05 00:00:00', 'MCD', 164.4635772705078)
('2019-02-06 00:00:00', 'MCD', 163.17617797851562)
('2019-02-07 00:00:00', 'MCD', 162.34262084960938)
('2019-02-08 00:00:00', 'MCD', 161.85171508789062)
('2019-02-11 00:00:00', 'MCD', 161.3979034423828)
('2019-02-12 00:00:00', 'MCD', 161.1292724609375)
('2019-02-13 00:00:00', 'MCD', 161.29598999023438)
('2019-02-14 00:00:00', 'MCD', 162.8890380859375)
('2019-02-15 00:00:00', 'MCD', 166.6864471435547)
('2019-02-19 00:00:00', 'MCD', 166.01959228515625)
('2019-02-20 00:00:00', 'MCD', 167.16806030273438)
('2019-02-21 00:00:00', 'MCD', 169.3168182373047)
('2019-02-22 00:00:00', 'MCD', 169.65025329589844)
('2019-02-25 00:00:00', 'MCD', 169.13156127929688)
('2019-02-26 00:00:00', 'MCD', 169.6873016357422)
('2019-02-27 00:00:00', 'MCD', 169.82623291015625)
('2019-02-28 00:00:00', 'MCD', 171.3548583984375)
('2019-03-01 00:00:00', 'MCD', 172.4827117919922)
('2019-03-04 00:00:00', 'MCD', 168.32557678222656)
('2019-03-05 00:00:00', 'MCD', 169.03396606445312)
('2019-03-06 00:00:00', 'MCD', 169.6677703857422)
('2019-03-07 00:00:00', 'MCD', 168.2603302001953)
('2019-03-08 00:00:00', 'MCD', 167.30958557128906)
('2019-03-11 00:00:00', 'MCD', 168.78231811523438)
('2019-03-12 00:00:00', 'MCD', 169.4813690185547)
('2019-03-13 00:00:00', 'MCD', 169.6957550048828)
('2019-03-14 00:00:00', 'MCD', 170.32957458496094)
('2019-03-15 00:00:00', 'MCD', 172.7436981201172)
('2019-03-18 00:00:00', 'MCD', 171.45738220214844)
('2019-03-19 00:00:00', 'MCD', 170.6744384765625)
('2019-03-20 00:00:00', 'MCD', 172.4081268310547)
('2019-03-21 00:00:00', 'MCD', 173.71302795410156)
('2019-03-22 00:00:00', 'MCD', 174.12315368652344)
('2019-03-25 00:00:00', 'MCD', 173.10719299316406)
('2019-03-26 00:00:00', 'MCD', 174.74765014648438)
('2019-03-27 00:00:00', 'MCD', 174.775634765625)
('2019-03-28 00:00:00', 'MCD', 176.5279541015625)
('2019-03-29 00:00:00', 'MCD', 177.00332641601562)
('2019-04-01 00:00:00', 'MCD', 175.59584045410156)
('2019-04-02 00:00:00', 'MCD', 175.5585479736328)
('2019-04-03 00:00:00', 'MCD', 175.5585479736328)
('2019-04-04 00:00:00', 'MCD', 176.97535705566406)
('2019-04-05 00:00:00', 'MCD', 177.75830078125)
('2019-04-08 00:00:00', 'MCD', 176.95669555664062)
('2019-04-09 00:00:00', 'MCD', 177.17108154296875)
('2019-04-10 00:00:00', 'MCD', 176.3695068359375)
('2019-04-11 00:00:00', 'MCD', 176.0525665283203)
('2019-04-12 00:00:00', 'MCD', 178.58782958984375)
('2019-04-15 00:00:00', 'MCD', 178.82089233398438)
('2019-04-16 00:00:00', 'MCD', 178.68109130859375)
('2019-04-17 00:00:00', 'MCD', 178.59719848632812)
('2019-04-18 00:00:00', 'MCD', 181.67308044433594)
('2019-04-22 00:00:00', 'MCD', 180.7502899169922)
('2019-04-23 00:00:00', 'MCD', 181.99929809570312)
('2019-04-24 00:00:00', 'MCD', 184.20835876464844)
('2019-04-25 00:00:00', 'MCD', 184.4879608154297)
('2019-04-26 00:00:00', 'MCD', 184.01258850097656)
('2019-04-29 00:00:00', 'MCD', 183.73297119140625)
('2019-04-30 00:00:00', 'MCD', 184.15240478515625)
('2019-05-01 00:00:00', 'MCD', 180.98330688476562)
('2019-05-02 00:00:00', 'MCD', 181.39344787597656)
('2019-05-03 00:00:00', 'MCD', 184.10581970214844)
('2019-05-06 00:00:00', 'MCD', 185.39208984375)
('2019-05-07 00:00:00', 'MCD', 184.5904998779297)
('2019-05-08 00:00:00', 'MCD', 184.58119201660156)
('2019-05-09 00:00:00', 'MCD', 184.30152893066406)
('2019-05-10 00:00:00', 'MCD', 186.40805053710938)
('2019-05-13 00:00:00', 'MCD', 185.5132598876953)
('2019-05-14 00:00:00', 'MCD', 184.56251525878906)
('2019-05-15 00:00:00', 'MCD', 185.5505828857422)
('2019-05-16 00:00:00', 'MCD', 186.40805053710938)
('2019-05-17 00:00:00', 'MCD', 185.6903533935547)
('2019-05-20 00:00:00', 'MCD', 185.4759979248047)
('2019-05-21 00:00:00', 'MCD', 186.26824951171875)
('2019-05-22 00:00:00', 'MCD', 186.38009643554688)
('2019-05-23 00:00:00', 'MCD', 185.4573516845703)
('2019-05-24 00:00:00', 'MCD', 184.33883666992188)
('2019-05-28 00:00:00', 'MCD', 183.3135223388672)
('2019-05-29 00:00:00', 'MCD', 182.7076873779297)
('2019-05-30 00:00:00', 'MCD', 185.70901489257812)
('2019-05-31 00:00:00', 'MCD', 185.8871307373047)
('2019-06-03 00:00:00', 'MCD', 186.36529541015625)
('2019-06-04 00:00:00', 'MCD', 187.16221618652344)
('2019-06-05 00:00:00', 'MCD', 187.6309814453125)
('2019-06-06 00:00:00', 'MCD', 190.3686065673828)
('2019-06-07 00:00:00', 'MCD', 192.64683532714844)
('2019-06-10 00:00:00', 'MCD', 188.7279052734375)
('2019-06-11 00:00:00', 'MCD', 190.5655059814453)
('2019-06-12 00:00:00', 'MCD', 192.13116455078125)
('2019-06-13 00:00:00', 'MCD', 191.71865844726562)
('2019-06-14 00:00:00', 'MCD', 192.4686737060547)
('2019-06-17 00:00:00', 'MCD', 191.0811309814453)
('2019-06-18 00:00:00', 'MCD', 191.73739624023438)
('2019-06-19 00:00:00', 'MCD', 191.77488708496094)
('2019-06-20 00:00:00', 'MCD', 192.30931091308594)
('2019-06-21 00:00:00', 'MCD', 191.50302124023438)
('2019-06-24 00:00:00', 'MCD', 191.18426513671875)
('2019-06-25 00:00:00', 'MCD', 192.86248779296875)
('2019-06-26 00:00:00', 'MCD', 191.77488708496094)
('2019-06-27 00:00:00', 'MCD', 193.3874969482422)
('2019-06-28 00:00:00', 'MCD', 194.690673828125)
('2019-07-01 00:00:00', 'MCD', 193.41561889648438)
('2019-07-02 00:00:00', 'MCD', 196.4907684326172)
('2019-07-03 00:00:00', 'MCD', 199.51904296875)
('2019-07-05 00:00:00', 'MCD', 198.04710388183594)
('2019-07-08 00:00:00', 'MCD', 198.90963745117188)
('2019-07-09 00:00:00', 'MCD', 198.843994140625)
('2019-07-10 00:00:00', 'MCD', 199.69717407226562)
('2019-07-11 00:00:00', 'MCD', 199.40652465820312)
('2019-07-12 00:00:00', 'MCD', 199.6878204345703)
('2019-07-15 00:00:00', 'MCD', 200.8316192626953)
('2019-07-16 00:00:00', 'MCD', 200.37220764160156)
('2019-07-17 00:00:00', 'MCD', 200.3628692626953)
('2019-07-18 00:00:00', 'MCD', 202.42543029785156)
('2019-07-19 00:00:00', 'MCD', 200.51283264160156)
('2019-07-22 00:00:00', 'MCD', 201.572265625)
('2019-07-23 00:00:00', 'MCD', 200.9253692626953)
('2019-07-24 00:00:00', 'MCD', 199.49090576171875)
('2019-07-25 00:00:00', 'MCD', 201.04722595214844)
('2019-07-26 00:00:00', 'MCD', 202.11602783203125)
('2019-07-29 00:00:00', 'MCD', 201.5535125732422)
('2019-07-30 00:00:00', 'MCD', 199.07838439941406)
('2019-07-31 00:00:00', 'MCD', 197.5595703125)
('2019-08-01 00:00:00', 'MCD', 198.0564727783203)
('2019-08-02 00:00:00', 'MCD', 201.08473205566406)
('2019-08-05 00:00:00', 'MCD', 197.30642700195312)
('2019-08-06 00:00:00', 'MCD', 200.70973205566406)
('2019-08-07 00:00:00', 'MCD', 203.2879638671875)
('2019-08-08 00:00:00', 'MCD', 204.394287109375)
('2019-08-09 00:00:00', 'MCD', 207.33815002441406)
('2019-08-12 00:00:00', 'MCD', 203.5973663330078)
('2019-08-13 00:00:00', 'MCD', 206.00685119628906)
('2019-08-14 00:00:00', 'MCD', 202.9598388671875)
('2019-08-15 00:00:00', 'MCD', 204.63803100585938)
('2019-08-16 00:00:00', 'MCD', 204.82554626464844)
('2019-08-19 00:00:00', 'MCD', 205.1161651611328)
('2019-08-20 00:00:00', 'MCD', 204.82554626464844)
('2019-08-21 00:00:00', 'MCD', 206.9256591796875)
('2019-08-22 00:00:00', 'MCD', 205.7818603515625)
('2019-08-23 00:00:00', 'MCD', 201.25352478027344)
('2019-08-26 00:00:00', 'MCD', 203.3629913330078)
('2019-08-27 00:00:00', 'MCD', 202.55670166015625)
('2019-08-28 00:00:00', 'MCD', 204.45054626464844)
('2019-08-29 00:00:00', 'MCD', 206.76625061035156)
('2019-08-30 00:00:00', 'MCD', 205.43731689453125)
('2019-09-03 00:00:00', 'MCD', 204.64564514160156)
('2019-09-04 00:00:00', 'MCD', 205.93687438964844)
('2019-09-05 00:00:00', 'MCD', 206.8699493408203)
('2019-09-06 00:00:00', 'MCD', 207.37889099121094)
('2019-09-09 00:00:00', 'MCD', 204.76815795898438)
('2019-09-10 00:00:00', 'MCD', 197.62400817871094)
('2019-09-11 00:00:00', 'MCD', 198.1140899658203)
('2019-09-12 00:00:00', 'MCD', 199.9519500732422)
('2019-09-13 00:00:00', 'MCD', 197.7465362548828)
('2019-09-16 00:00:00', 'MCD', 195.47508239746094)
('2019-09-17 00:00:00', 'MCD', 197.7842254638672)
('2019-09-18 00:00:00', 'MCD', 198.33087158203125)
('2019-09-19 00:00:00', 'MCD', 198.41567993164062)
('2019-09-20 00:00:00', 'MCD', 197.35064697265625)
('2019-09-23 00:00:00', 'MCD', 199.3770294189453)
('2019-09-24 00:00:00', 'MCD', 199.82945251464844)
('2019-09-25 00:00:00', 'MCD', 200.40438842773438)
('2019-09-26 00:00:00', 'MCD', 200.37611389160156)
('2019-09-27 00:00:00', 'MCD', 200.90390014648438)
('2019-09-30 00:00:00', 'MCD', 202.36477661132812)
('2019-10-01 00:00:00', 'MCD', 197.00196838378906)
('2019-10-02 00:00:00', 'MCD', 194.41006469726562)
('2019-10-03 00:00:00', 'MCD', 197.95387268066406)
('2019-10-04 00:00:00', 'MCD', 199.5184326171875)
('2019-10-07 00:00:00', 'MCD', 199.73519897460938)
('2019-10-08 00:00:00', 'MCD', 198.97177124023438)
('2019-10-09 00:00:00', 'MCD', 200.5928955078125)
('2019-10-10 00:00:00', 'MCD', 199.58438110351562)
('2019-10-11 00:00:00', 'MCD', 197.00196838378906)
('2019-10-14 00:00:00', 'MCD', 196.39874267578125)
('2019-10-15 00:00:00', 'MCD', 195.30543518066406)
('2019-10-16 00:00:00', 'MCD', 196.32333374023438)
('2019-10-17 00:00:00', 'MCD', 194.95669555664062)
('2019-10-18 00:00:00', 'MCD', 196.5118408203125)
('2019-10-21 00:00:00', 'MCD', 197.7842254638672)
('2019-10-22 00:00:00', 'MCD', 187.81253051757812)
('2019-10-23 00:00:00', 'MCD', 187.75599670410156)
('2019-10-24 00:00:00', 'MCD', 184.7493896484375)
('2019-10-25 00:00:00', 'MCD', 183.42047119140625)
('2019-10-28 00:00:00', 'MCD', 180.753173828125)
('2019-10-29 00:00:00', 'MCD', 181.54490661621094)
('2019-10-30 00:00:00', 'MCD', 185.5694122314453)
('2019-10-31 00:00:00', 'MCD', 185.39031982421875)
('2019-11-01 00:00:00', 'MCD', 182.7889862060547)
('2019-11-04 00:00:00', 'MCD', 177.8125762939453)
('2019-11-05 00:00:00', 'MCD', 181.13018798828125)
('2019-11-06 00:00:00', 'MCD', 183.0151824951172)
('2019-11-07 00:00:00', 'MCD', 181.97845458984375)
('2019-11-08 00:00:00', 'MCD', 182.47799682617188)
('2019-11-11 00:00:00', 'MCD', 181.56375122070312)
('2019-11-12 00:00:00', 'MCD', 182.1669464111328)
('2019-11-13 00:00:00', 'MCD', 183.78805541992188)
('2019-11-14 00:00:00', 'MCD', 182.84555053710938)
('2019-11-15 00:00:00', 'MCD', 182.81727600097656)
('2019-11-18 00:00:00', 'MCD', 183.1094512939453)
('2019-11-19 00:00:00', 'MCD', 182.3177490234375)
('2019-11-20 00:00:00', 'MCD', 182.9680938720703)
('2019-11-21 00:00:00', 'MCD', 181.2904052734375)
('2019-11-22 00:00:00', 'MCD', 182.03500366210938)
('2019-11-25 00:00:00', 'MCD', 180.8568572998047)
('2019-11-26 00:00:00', 'MCD', 182.85496520996094)
('2019-11-27 00:00:00', 'MCD', 185.0133056640625)
('2019-11-29 00:00:00', 'MCD', 184.47265625)
('2019-12-02 00:00:00', 'MCD', 185.13661193847656)
('2019-12-03 00:00:00', 'MCD', 183.18263244628906)
('2019-12-04 00:00:00', 'MCD', 184.31137084960938)
('2019-12-05 00:00:00', 'MCD', 184.21652221679688)
('2019-12-06 00:00:00', 'MCD', 185.29786682128906)
('2019-12-09 00:00:00', 'MCD', 184.66232299804688)
('2019-12-10 00:00:00', 'MCD', 184.91845703125)
('2019-12-11 00:00:00', 'MCD', 184.70028686523438)
('2019-12-12 00:00:00', 'MCD', 186.20846557617188)
('2019-12-13 00:00:00', 'MCD', 186.97679138183594)
('2019-12-16 00:00:00', 'MCD', 187.6976776123047)
('2019-12-17 00:00:00', 'MCD', 186.4076690673828)
('2019-12-18 00:00:00', 'MCD', 185.56344604492188)
('2019-12-19 00:00:00', 'MCD', 186.9198455810547)
('2019-12-20 00:00:00', 'MCD', 186.99575805664062)
('2019-12-23 00:00:00', 'MCD', 186.1041259765625)
('2019-12-24 00:00:00', 'MCD', 186.5499267578125)
('2019-12-26 00:00:00', 'MCD', 186.9198455810547)
('2019-12-27 00:00:00', 'MCD', 187.9727325439453)
('2019-12-30 00:00:00', 'MCD', 186.77760314941406)
('2019-12-31 00:00:00', 'MCD', 187.4415740966797)
('2020-01-02 00:00:00', 'MCD', 190.4579315185547)
('2020-01-03 00:00:00', 'MCD', 189.78445434570312)
('2020-01-06 00:00:00', 'MCD', 191.918701171875)
('2020-01-07 00:00:00', 'MCD', 192.2032470703125)
('2020-01-08 00:00:00', 'MCD', 195.31446838378906)
('2020-01-09 00:00:00', 'MCD', 197.62893676757812)
('2020-01-10 00:00:00', 'MCD', 196.60450744628906)
('2020-01-13 00:00:00', 'MCD', 195.88357543945312)
('2020-01-14 00:00:00', 'MCD', 196.6519012451172)
('2020-01-15 00:00:00', 'MCD', 198.97584533691406)
('2020-01-16 00:00:00', 'MCD', 200.00030517578125)
('2020-01-17 00:00:00', 'MCD', 201.07212829589844)
('2020-01-21 00:00:00', 'MCD', 200.29434204101562)
('2020-01-22 00:00:00', 'MCD', 200.55992126464844)
('2020-01-23 00:00:00', 'MCD', 202.4380340576172)
('2020-01-24 00:00:00', 'MCD', 200.3702392578125)
('2020-01-27 00:00:00', 'MCD', 198.56800842285156)
('2020-01-28 00:00:00', 'MCD', 199.56394958496094)
('2020-01-29 00:00:00', 'MCD', 203.4055633544922)
('2020-01-30 00:00:00', 'MCD', 205.05599975585938)
('2020-01-31 00:00:00', 'MCD', 202.95974731445312)
('2020-02-03 00:00:00', 'MCD', 204.10745239257812)
('2020-02-04 00:00:00', 'MCD', 203.5762939453125)
('2020-02-05 00:00:00', 'MCD', 203.33914184570312)
('2020-02-06 00:00:00', 'MCD', 201.9163360595703)
('2020-02-07 00:00:00', 'MCD', 200.72116088867188)
('2020-02-10 00:00:00', 'MCD', 202.23883056640625)
('2020-02-11 00:00:00', 'MCD', 204.62916564941406)
('2020-02-12 00:00:00', 'MCD', 206.2701416015625)
('2020-02-13 00:00:00', 'MCD', 206.23220825195312)
('2020-02-14 00:00:00', 'MCD', 205.919189453125)
('2020-02-18 00:00:00', 'MCD', 205.02755737304688)
('2020-02-19 00:00:00', 'MCD', 204.53433227539062)
('2020-02-20 00:00:00', 'MCD', 204.01260375976562)
('2020-02-21 00:00:00', 'MCD', 204.761962890625)
('2020-02-24 00:00:00', 'MCD', 202.53289794921875)
('2020-02-25 00:00:00', 'MCD', 201.1859588623047)
('2020-02-26 00:00:00', 'MCD', 199.28887939453125)
('2020-02-27 00:00:00', 'MCD', 190.65713500976562)
('2020-02-28 00:00:00', 'MCD', 185.33116149902344)
('2020-03-02 00:00:00', 'MCD', 193.32968139648438)
('2020-03-03 00:00:00', 'MCD', 190.42803955078125)
('2020-03-04 00:00:00', 'MCD', 197.59620666503906)
('2020-03-05 00:00:00', 'MCD', 189.29222106933594)
('2020-03-06 00:00:00', 'MCD', 189.8076629638672)
('2020-03-09 00:00:00', 'MCD', 178.3538818359375)
('2020-03-10 00:00:00', 'MCD', 190.7621307373047)
('2020-03-11 00:00:00', 'MCD', 179.6806182861328)
('2020-03-12 00:00:00', 'MCD', 162.38548278808594)
('2020-03-13 00:00:00', 'MCD', 169.06683349609375)
('2020-03-16 00:00:00', 'MCD', 142.2268829345703)
('2020-03-17 00:00:00', 'MCD', 140.90016174316406)
('2020-03-18 00:00:00', 'MCD', 131.04994201660156)
('2020-03-19 00:00:00', 'MCD', 142.694580078125)
('2020-03-20 00:00:00', 'MCD', 141.73056030273438)
('2020-03-23 00:00:00', 'MCD', 130.8590545654297)
('2020-03-24 00:00:00', 'MCD', 154.5778350830078)
('2020-03-25 00:00:00', 'MCD', 155.56094360351562)
('2020-03-26 00:00:00', 'MCD', 159.73199462890625)
('2020-03-27 00:00:00', 'MCD', 156.54403686523438)
('2020-03-30 00:00:00', 'MCD', 160.47653198242188)
('2020-03-31 00:00:00', 'MCD', 157.82305908203125)
('2020-04-01 00:00:00', 'MCD', 150.9698944091797)
('2020-04-02 00:00:00', 'MCD', 154.14833068847656)
('2020-04-03 00:00:00', 'MCD', 153.03158569335938)
('2020-04-06 00:00:00', 'MCD', 168.98092651367188)
('2020-04-07 00:00:00', 'MCD', 167.59693908691406)
('2020-04-08 00:00:00', 'MCD', 169.41043090820312)
('2020-04-09 00:00:00', 'MCD', 175.33775329589844)
('2020-04-13 00:00:00', 'MCD', 171.9207000732422)
('2020-04-14 00:00:00', 'MCD', 175.6145477294922)
('2020-04-15 00:00:00', 'MCD', 169.74449157714844)
('2020-04-16 00:00:00', 'MCD', 171.3289337158203)
('2020-04-17 00:00:00', 'MCD', 177.62852478027344)
('2020-04-20 00:00:00', 'MCD', 173.3810577392578)
('2020-04-21 00:00:00', 'MCD', 169.496337890625)
('2020-04-22 00:00:00', 'MCD', 177.99118041992188)
('2020-04-23 00:00:00', 'MCD', 173.75331115722656)
('2020-04-24 00:00:00', 'MCD', 175.64317321777344)
('2020-04-27 00:00:00', 'MCD', 177.42807006835938)
('2020-04-28 00:00:00', 'MCD', 177.4662322998047)
('2020-04-29 00:00:00', 'MCD', 179.2702178955078)
('2020-04-30 00:00:00', 'MCD', 179.0220489501953)
('2020-05-01 00:00:00', 'MCD', 174.34512329101562)
('2020-05-04 00:00:00', 'MCD', 173.59104919433594)
('2020-05-05 00:00:00', 'MCD', 171.08079528808594)
('2020-05-06 00:00:00', 'MCD', 168.9141082763672)
('2020-05-07 00:00:00', 'MCD', 172.8751983642578)
('2020-05-08 00:00:00', 'MCD', 172.98016357421875)
('2020-05-11 00:00:00', 'MCD', 172.64613342285156)
('2020-05-12 00:00:00', 'MCD', 168.50364685058594)
('2020-05-13 00:00:00', 'MCD', 164.95301818847656)
('2020-05-14 00:00:00', 'MCD', 167.4251251220703)
('2020-05-15 00:00:00', 'MCD', 165.89794921875)
('2020-05-18 00:00:00', 'MCD', 171.64393615722656)
('2020-05-19 00:00:00', 'MCD', 171.395751953125)
('2020-05-20 00:00:00', 'MCD', 175.7195587158203)
('2020-05-21 00:00:00', 'MCD', 176.6549530029297)
('2020-05-22 00:00:00', 'MCD', 176.01544189453125)
('2020-05-26 00:00:00', 'MCD', 176.42584228515625)
('2020-05-27 00:00:00', 'MCD', 179.1747589111328)
('2020-05-28 00:00:00', 'MCD', 180.13877868652344)
('2020-05-29 00:00:00', 'MCD', 179.02420043945312)
('2020-06-01 00:00:00', 'MCD', 180.07151794433594)
('2020-06-02 00:00:00', 'MCD', 180.2444610595703)
('2020-06-03 00:00:00', 'MCD', 185.7212677001953)
('2020-06-04 00:00:00', 'MCD', 185.67323303222656)
('2020-06-05 00:00:00', 'MCD', 189.43972778320312)
('2020-06-08 00:00:00', 'MCD', 194.7147674560547)
('2020-06-09 00:00:00', 'MCD', 191.70733642578125)
('2020-06-10 00:00:00', 'MCD', 188.13299560546875)
('2020-06-11 00:00:00', 'MCD', 180.16758728027344)
('2020-06-12 00:00:00', 'MCD', 181.7626190185547)
('2020-06-15 00:00:00', 'MCD', 182.07008361816406)
('2020-06-16 00:00:00', 'MCD', 182.86758422851562)
('2020-06-17 00:00:00', 'MCD', 183.31915283203125)
('2020-06-18 00:00:00', 'MCD', 182.07008361816406)
('2020-06-19 00:00:00', 'MCD', 179.25479125976562)
('2020-06-22 00:00:00', 'MCD', 180.11956787109375)
('2020-06-23 00:00:00', 'MCD', 179.3124542236328)
('2020-06-24 00:00:00', 'MCD', 177.07369995117188)
('2020-06-25 00:00:00', 'MCD', 175.60357666015625)
('2020-06-26 00:00:00', 'MCD', 172.7018585205078)
('2020-06-29 00:00:00', 'MCD', 175.6420440673828)
('2020-06-30 00:00:00', 'MCD', 177.2466583251953)
('2020-07-01 00:00:00', 'MCD', 177.42919921875)
('2020-07-02 00:00:00', 'MCD', 176.33384704589844)
('2020-07-06 00:00:00', 'MCD', 181.1188201904297)
('2020-07-07 00:00:00', 'MCD', 178.54379272460938)
('2020-07-08 00:00:00', 'MCD', 178.57261657714844)
('2020-07-09 00:00:00', 'MCD', 177.11212158203125)
('2020-07-10 00:00:00', 'MCD', 177.6405792236328)
('2020-07-13 00:00:00', 'MCD', 177.67901611328125)
('2020-07-14 00:00:00', 'MCD', 183.2519073486328)
('2020-07-15 00:00:00', 'MCD', 184.2607879638672)
('2020-07-16 00:00:00', 'MCD', 183.44407653808594)
('2020-07-17 00:00:00', 'MCD', 183.98214721679688)
('2020-07-20 00:00:00', 'MCD', 184.1070556640625)
('2020-07-21 00:00:00', 'MCD', 185.4234161376953)
('2020-07-22 00:00:00', 'MCD', 190.8425750732422)
('2020-07-23 00:00:00', 'MCD', 189.81446838378906)
('2020-07-24 00:00:00', 'MCD', 190.93865966796875)
('2020-07-27 00:00:00', 'MCD', 193.36959838867188)
('2020-07-28 00:00:00', 'MCD', 188.55575561523438)
('2020-07-29 00:00:00', 'MCD', 188.52696228027344)

('2021-05-25 00:00:00', 'HD', 312.2125244140625)
('2021-05-26 00:00:00', 'HD', 312.7842102050781)
('2021-05-27 00:00:00', 'HD', 314.2035827636719)
('2021-05-28 00:00:00', 'HD', 314.3415832519531)

In [53]:
#store the results of the request in a  dataframe result
result = pd.DataFrame(cur.execute(query.replace('\n',' ')), columns = ['Date', 'ticker', 'price'])
result

                     Date ticker       price
0     2019-01-02 00:00:00     BA  314.645142
1     2019-01-03 00:00:00     BA  302.100555
2     2019-01-04 00:00:00     BA  317.822601
3     2019-01-07 00:00:00     BA  318.823395
4     2019-01-08 00:00:00     BA  330.891937
...                   ...    ...         ...
2423  2021-05-24 00:00:00     HD  310.329895
2424  2021-05-25 00:00:00     HD  312.212524
2425  2021-05-26 00:00:00     HD  312.784210
2426  2021-05-27 00:00:00     HD  314.203583
2427  2021-05-28 00:00:00     HD  314.341583

[2428 rows x 3 columns]